### ISSUE TITLE
The Ability to Change Color of scene

### ISSUE THREAD

**Issue by freetoplay123** [Beg-in/vue-babylonjs#12]
I am trying to change the color of the scene to match my website's color. I am not sure what would be the best option of doing that.

I would think of something like this in my methods:

```
activeScene() {
      if (this.scene !== null) {
        this.scene.clearColor = new this.BABYLON.Color4(0,0,0,0);
} 
```

I have also tried:

```
 <Scene v-model="scene">
     <Property name="clearColor" :color="$color(0, 0, 0, 0)"></Property>
  </Scene>
```

Both of the ways that I have been doing it doesn't seem to work. Not sure if this is a bug or not.

**Comment by Kjue** [comment]
That should work splendidly. Maybe you are setting the color to when the scene is not adjusted yet? See [this PG](https://www.babylonjs-playground.com/#BMQ2GZ#3) for an example and play with the clearColor at the end of the code. You'll notice the background may be anything else too.

I'll chime in on this as I've looked into background colors a lot. I tried to apply a transparent fog some time ago and discovered it was using Color3 construct. It would make sense to apply Color4 there as well, so that the scene may fade into the page or be the background for a page. I admit too, that I may have missed the change if it did come through already.

I could imagine a _Jaws Comeback_ movie page having a shark slowly creeping and fading in from the background when user is looking at the content. 🤣

**Comment by joestrouth1** [comment]
I also cannot figure this out. 

Here's a reproduction https://codesandbox.io/s/w65870qvo8

Tried it in a watcher, as a Property component, and as a method. The most I can get is a brief flash of the color before the default covers it again.

**Comment by joestrouth1** [comment]
The default scene creates a pre-configured environment, with a skybox and ground. Those two things will block you from seeing your `clearColor` in the background of the scene. 

- You can change the color of them with `main` 
 ```Vue
<Scene :main="$color(1, 0, 0)">
```
- You can change each color individually by passing an object to `environment` 
```Vue
<Scene v-model="myScene"
  :environment="{
    skyboxColor: $color(1,0,0),
    groundColor: $color(1,0,0)
  }"
>
```
or turn them on/off to let your `clearColor` through
```Vue
<Scene v-model="myScene" :environment="{ createSkybox: false }">
```
- Creating your own `Camera` in the scene will also prevent the creation of the default environment
```Vue
<Scene v-model="myScene">
  <Camera type="universal"/>
```

**Comment by BrainBacon** [comment]
Great advice @joestrouth1 thanks for the help! Don't forget that on props that expect colors you can also refer to them by an HTML color code or an array of values instead of a call to `$color`, just don't forget you don't need to bind string values with `:` or `v-bind:` e.g.
```vue
<Scene main="#FF0000">
```
