### ISSUE TITLE
Discrepancies between require and import

### ISSUE THREAD

**Issue by Kasparsu** [Beg-in/vue-babylonjs#6]
Was trying to use it with vue that comes with laravel. Vue is scaffolded and ready to go. By default it uses require to include modules and so on so I used that from the example and didn't work. used import and it works. It seems that import and require are doing things differently and that makes Vue.use not work. 
Found workaround for the moment.

```
let vb = require('vue-babylonjs');
Vue.use(vb.default);
```

**Comment by BrainBacon** [comment]
I'm unfamiliar with laravel, do you have a webpack config or similar? Perhaps it's using the "module" definition from package.json. You should be able to remedy this by using `require('vue-babylonjs/dist/umd.js')`, by setting an alias to that script, or by making sure your config is using the "main" export of the library instead of "module".

**Comment by BrainBacon** [comment]
I'm going to close this, if you're still having trouble just post an update on here and we can re-open if there's a problem.
