### ISSUE TITLE
WebVRFreeCamera

### ISSUE THREAD

**Issue by rtwins** [Beg-in/vue-babylonjs#9]
Hi, 
First at all, great job with this library!

I'm trying to create a WebVRFreeCamera but it iseems that is not currently available as a vue component (or I'm not finding it), so I've tried creating it using the standard BABYLON.WebVRFreeCamera from the scene watch:

```
watch: {
      myScene () {
        // myScene is now available from the component
        // do something with it here or call a method to use it from here
        this.BABYLON.WebVRFreeCamera('vrcam0', new this.BABYLON.Vector3(0, 0, 0), this.myScene)
      },
}
```
but is returning an error: ' Cannot add property state, object is not extensible' on the Babylonjs 'Node' parent of the camera.

This, obviously, happens even creating just a Node or a Light but doesn't seems to happen on a Mesh, using:

`this.BABYLON.Mesh('boop', this.myScene)`
or
`this.BABYLON.MeshBuilder.CreateBox('box', {height: 5}, this.myScene)`

So the real question is, what am i doing wrong? :)

Thanks in advance

**Comment by BrainBacon** [comment]
Hi, thanks for the report. I am away on vacation for the next couple weeks, but I may find a bit of time to look at this after a bit. It would help immensely if you could make a minimal reproduction of the issue on Glitch or something similar that I can peek at. Otherwise it will be a while before I can dedicate some time to setting up a reproducible error.

Also, I am planning at some point to produce a more complete package for the WebVR stuff in general. If you are interested in helping you can start work on planning out the necessary components and changes.

**Comment by rtwins** [comment]
Hi,
Nevermind I'm dumb, 

I was missing the NEW creating the camera....

`var camera = new  this.BABYLON.WebVRFreeCamera('vrcam0', new this.BABYLON.Vector3(0, 0, 0), this.myScene)`

It works perfectly fine doing it right... :)

Sorry and thanks for your time.

I'll give a look about including WebVR, hope I can help!

**Comment by BrainBacon** [comment]
No worries, thanks for the issue anyways. It's always nice to have a history of common mistakes. Perhaps it would be good to pool these together into an FAQ at some point.
